In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

**Creating array**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**Multidiamentional array**

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0][0] = 10
n

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[0,2] = 20
n

array([[10,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[1]

array([4, 5, 6])

In [25]:
n[:]

array([[10,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n[:, 2]

array([20,  6,  9])

In [73]:
n[0, 2]

np.int64(3)

**Random numbers**

In [35]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [36]:
np.random.seed(10)
np.random.randn(5,2) # normal distribution

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [47]:
np.random.randint(low=0, high=100, size=(5,2)) # random integers

array([[80, 41],
       [90, 12],
       [30, 81],
       [17, 16],
       [ 0, 31]])

**Element wise operation**

In [49]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [63]:
b = ((a + 1) ** 2) / 2
b

array([ 0.5,  2. ,  4.5,  8. , 12.5])

In [64]:
a + b

array([ 0.5,  3. ,  6.5, 11. , 16.5])

**Comparision operator**

In [55]:
a

array([0, 1, 2, 3, 4])

In [56]:
a >= 2

array([False, False,  True,  True,  True])

In [68]:
b = np.array([1,0,4,3,4])
b

array([1, 0, 4, 3, 4])

In [70]:
a >= b

array([False,  True, False,  True,  True])

In [71]:
a[a>=b]

array([1, 3, 4])

In [75]:
arr1 = np.ones(4)
arr1

array([1., 1., 1., 1.])

In [76]:
arr2 = np.full(4, 3)
arr2

array([3, 3, 3, 3])

In [ ]:
result = arr1 + arr2  # Element-wise addition
result = arr1 / arr2  # Element-wise division